### PR TITLE
add town Fortaleza

### PR DESCRIPTION
**Pull request by 1bertovalente**
add town Fortaleza, from Brazil

### CODE REVIEW

**Comment by Kryze** [comment]
Hello, I should have mention it in the README but could you possibly put the description in english ?

**Comment by 1bertovalente** [comment]
Hi @Kryze, done.

**Comment by Kryze** [comment]
Hello, after watching your changes, I saw that you move a town to another ID and let the ID 3 empty, can you check that ? :)

**Comment by 1bertovalente** [comment]
Hello, corrected and added longitude and latidude. Sorry, I must have confused myself

**Comment by Kryze** [comment]
Thank you ! No problem everything is fine now !

**Comment by 1bertovalente** [comment]
Tks, @Kryze! Good job. If you have more projects, I'm happy to help.

**Pull request merged**
